import json
import ast
import os
from app.amazon_predictor import amazon_demo_inference

def get_amazon_batch_anomalies():
    sample_file = "data/amazon/raw/sample_reviews.json"
    results_file = "reports/amazon_tgat_results.json"
    
    threshold = 0.52
    if os.path.exists(results_file):
        with open(results_file, "r") as f:
            res = json.load(f)
            threshold = res.get("Threshold", 0.52)
            
    interactions = []
    if os.path.exists(sample_file):
        with open(sample_file, "r", encoding="utf-8") as f:
            for line in f:
                try:
                    data = ast.literal_eval(line)
                    interactions.append(data)
                except:
                    pass
    
    analyzed = []
    anomalous_count = 0
    
    # We will limit to 100 for safety, but interactions has ~100
    for data in interactions[:100]:
        reviewer_id = data.get("reviewerID", "UNKNOWN")
        asin = data.get("asin", "UNKNOWN")
        unix_time = data.get("unixReviewTime", 0)
        rating = float(data.get("overall", 5.0))
        
        # Run real TGAT inference
        inf = amazon_demo_inference({
            "reviewerID": reviewer_id,
            "asin": asin,
            "unixReviewTime": unix_time,
            "overall": rating
        })
        
        prob = inf.get("anomaly_probability", 0.0)
        is_anomalous = prob >= threshold
        if is_anomalous:
            anomalous_count += 1
            
        analyzed.append({
            "reviewerID": reviewer_id,
            "asin": asin,
            "unixReviewTime": unix_time,
            "rating": rating,
            "anomaly_probability": prob,
            "is_anomalous": is_anomalous
        })
        
    analyzed.sort(key=lambda x: x["unixReviewTime"])
    
    return {
        "status": "success",
        "provenance": "Scores generated by the trained Amazon TGAT checkpoint; no synthetic interactions.",
        "kpi": {
            "total_analyzed": len(analyzed),
            "anomalous_count": anomalous_count,
            "anomaly_rate": round(anomalous_count / max(1, len(analyzed)) * 100, 2),
            "threshold": threshold
        },
        "time_series": analyzed
    }
