"""
app/analytics_anomalies.py
==========================
Serves TGAT batch anomaly analytics for the dashboard.

Uses DEMO_BATCH_THRESHOLD (75th percentile of cold-start score distribution = 0.6939)
rather than the training threshold (0.52), because the dashboard runs in cold-start
mode without historical graph edges. See app/amazon_predictor.py docstring for full
root-cause explanation.
"""

import json
import ast
import os
from app.amazon_predictor import amazon_demo_inference, DEMO_BATCH_THRESHOLD, TRAINING_THRESHOLD


def get_amazon_batch_anomalies():
    sample_file = "data/amazon/raw/sample_reviews.json"

    # Use calibrated demo-mode threshold, NOT the raw training threshold
    threshold = DEMO_BATCH_THRESHOLD
    threshold_source = (
        "Demo-mode calibration: 75th-percentile of cold-start score distribution "
        f"(seed=42, n=100; training threshold={TRAINING_THRESHOLD} not applicable in cold-start mode)"
    )

    interactions = []
    if os.path.exists(sample_file):
        with open(sample_file, "r", encoding="utf-8") as f:
            for line in f:
                try:
                    data = ast.literal_eval(line)
                    interactions.append(data)
                except Exception:
                    pass

    analyzed = []
    anomalous_count = 0

    for data in interactions[:100]:
        reviewer_id = data.get("reviewerID", "UNKNOWN")
        asin = data.get("asin", "UNKNOWN")
        unix_time = data.get("unixReviewTime", 0)
        rating = float(data.get("overall", 5.0))

        inf = amazon_demo_inference({
            "reviewerID": reviewer_id,
            "asin": asin,
            "unixReviewTime": unix_time,
            "overall": rating
        })

        prob = inf.get("anomaly_probability", 0.0) or 0.0
        is_anomalous = prob >= threshold
        if is_anomalous:
            anomalous_count += 1

        analyzed.append({
            "reviewerID": reviewer_id,
            "asin": asin,
            "unixReviewTime": unix_time,
            "rating": rating,
            "anomaly_probability": round(prob, 4),
            "similarity_score": inf.get("similarity_score", 0.0),
            "is_anomalous": is_anomalous,
            "risk_level": inf.get("risk_level", "LOW")
        })

    analyzed.sort(key=lambda x: x["unixReviewTime"])

    normal_count = len(analyzed) - anomalous_count
    avg_score = round(sum(r["anomaly_probability"] for r in analyzed) / max(1, len(analyzed)), 4)

    return {
        "status": "success",
        "provenance": (
            "Scores generated by the trained Amazon TGAT checkpoint (models/amazon_tgat.pt). "
            "Cold-start demo mode: deterministic fixed-seed node features, no historical edge graph. "
            "No synthetic interactions. Real Amazon Electronics reviewerIDs and ASINs."
        ),
        "threshold_info": {
            "value": threshold,
            "source": threshold_source,
            "training_threshold": TRAINING_THRESHOLD
        },
        "kpi": {
            "total_analyzed": len(analyzed),
            "anomalous_count": anomalous_count,
            "normal_count": normal_count,
            "anomaly_rate": round(anomalous_count / max(1, len(analyzed)) * 100, 2),
            "threshold": round(threshold, 4),
            "avg_anomaly_score": avg_score
        },
        "time_series": analyzed
    }
